### PR TITLE
add depends-dot, replacement of rxdep

### PR DESCRIPTION
**Pull request by k-okada**
Add depends-dot command in order to provide equivalent function of rxdeps (http://www.ros.org/wiki/rxdeps).  use following command to see depends tree:

rospack depends-dot roscpp | dot | xdot -

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I am not sure that it is a good idea to extend rospack with dot-specific functionality. Wouldn't it be much easier and cleaner to write a simple script/program which uses rospack and outputs the dot formatted data? I am not sure if that would require changes to rospack to provide the necessary information.

**Comment by k-okada** [comment]
Humm, in that case we need to add 
class Rostree : public Rosstackage {
}
in rospack.h. Is it ok?

**Comment by dirk-thomas** [comment]
What features / API would that Rostree class need to provide?

**Comment by k-okada** [comment]
First, we need Rostree::usage() method to provide command line options,
Then, we also need following strucutre

```
std::map<std::string, std::vector<std::string> > dot_deps;
```

that stores "map(parent, [children1, children2, ...])" style information, by calling following code recursively in the Rosstackage(or Rostree) class.

```
{
  std::string indented_dep;
  std::vector<std::string>& deps = dot_deps[stackage->name_];
  // check if it->names is already stored
  if  ( std::find( deps.begin(), deps.end(), (*it)->name_ ) == deps.end() ) {
      deps.push_back((*it)->name_);
  }
}
```

**Comment by dirk-thomas** [comment]
Without knowing how the algorithm should work I would guess that it should be possible to implement that on-top of the existing API. Could you try to implement your own main function and build an executable which achieves your desired feature and just links to the rospack library?

**Comment by k-okada** [comment]
Ok, see https://github.com/k-okada/rospack/blob/groovy-devel/src/rostree_main.cpp
I have to move several methods to public and declare stackage in rospack.h, hope you understand what I need.
I just need the list of "A"->"B" style information( this  indicates A depends on B) for all package A that depends on the interest package. I meant to this program performs similar function as "debtree"  program

**Comment by dirk-thomas** [comment]
Reading your main file it looks to me that it perform roughly the following:

```
rp = RosPack()
rp.crawl()
rp.find(pkg_name)
vector<string> deps_on
rp.depsOn(pkg_name, deps_on)
foreach dep_on in deps_on:
  vector<string> deps
  rp.deps(dep_on, deps)
  foreach dep in deps:
    print(dep_on + " -> " + dep)
```

This pseudo only uses already existing public API to achieve the same functionality. Is there anything else you need which I have overlooked and which requires functionality which is currently not exposed / available?

**Comment by k-okada** [comment]
Thanks,  rewrite codes. see https://github.com/ros/rospack/pull/13, I also interested in if you plan to support rosstack contains in wet package ( #14 )

**Comment by dirk-thomas** [comment]
Superseded by #13

**Pull request closed without merging**
