### PR TITLE
consider package as wet if package.xml exists

### PR DESCRIPTION
**Pull request by k-okada**
this is the patch to consider the package as wet if package.xml exists. current implementation regards the package as dry if manifest.xml, this means that if the package has both manifest.xml and package.xml then it consider the package as dry.
https://github.com/ros-infrastructure/rospkg/pull/55

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This patch can not be merged. The semantic of rospack can't be changed since there are numerous cases which depend on the current behavior.

**Comment by davetcoleman** [comment]
this would have been really nice to have had, though. For example: https://github.com/ros-controls/ros_control/commit/0ced0d140304aabfe01a099756d5b5082c71bef8

**Comment by dirk-thomas** [comment]
I will close this pull request since this behavior must stay as it is for a good reason.

If you have further comments please feel free to continue writing on this ticket.

**Comment by gerkey** [comment]
Worth considering a switch (e.g., env var) to enable the new behavior? By default, the current behavior is used, but users who want the new behavior can have it.

**Comment by dirk-thomas** [comment]
I think that inverting the logic is neither a good idea nor necessary.

First the _rosbuild_ stuff entirely is bases on the current model. I would guess that it will break a numerous ways when this is changed. So practically change the behavior will make dry stuff unusable without a lot of work finding the regressions.

Second there is no need to change the behavior. A package should not be a hybrid in the first place. It should be either _wet_ or _dry_. There are other cases where problems will raise if we allow hybrid packages which are not worth dealing with. Having separate branches for the _rosbuild_ and _catkin_ version of a package is not a high burden for the maintainer.

**Comment by k-okada** [comment]
This is just a comment: 

I understand that inverting the logic is bad idea and it is easy and clean to have separate branch.

However, having branch for different distribution is very dangerous as explained in [1] for the lab that have several different robots and projects. For example, PCL developers uses hydro, pr2 users uses groovy, drcsim/hrp/schaft team uses fuerte. Each branch will grow separately and when some robot is able to update to the groovy, then their code in fuerte is not able to merge into groovy branch and they will create new package. I think this would be one reason to reinventing wheels as seen in [2].

For the group have several robots with different distribution, they will have same problem that I have. We want to mix up the effeorts/codes developed on different robots/distributions.

So if there are better way than creating hybrid packages, that would be ok for me. For example, wet/dry problem will disappear with in a few years. So what we need is using same package.xml for different distributions as described in [3]. Or if there are online conversion of different version of message as we have in rosbag migration, that may solve my problem.

[1] https://github.com/ros-infrastructure/rospkg/pull/55#issuecomment-34579711
[2] http://www.willowgarage.com/blog/2010/04/27/reinventing-wheel
[3] https://github.com/ros-infrastructure/rosdep/issues/298

**Pull request closed without merging**
