### PR TITLE
add rostree, write package dependency as dot format

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The implementation looks good and does not require any changes to the existing API.

But one important goal we have is to keep the core libraries and tools as small and stable as possible. Therefore my earlier comment (https://github.com/ros/rospack/pull/12#issuecomment-15886578) was meant that it might make sense to release this as a separate package (and not as part of rospack). Would you go ahead and create a separate package (i.e. rostree, or may be something with "dot" in the name to clarify what the tool does) and release that?

**Comment by dirk-thomas** [comment]
Closing this pull request since the code of it should be released as a separate package. That makes it easier to maintain and enhance in the future and not tie it to a core package like rospack.

**Comment by jbohren** [comment]
> Closing this pull request since the code of it should be released as a separate package. That makes it easier to maintain and enhance in the future and not tie it to a core package like rospack.

Closing this PR only seems to have limited the availability of a potentially useful tool.

I think this should be re-opened, it's something that could be extremely useful for debugging complex workspace build problems (i.e. https://github.com/ros/catkin/issues/539).

**Comment by tkruse** [comment]
Please see the rqt_dep tool as well for similar purposes:
http://wiki.ros.org/rqt_dep

**Comment by dirk-thomas** [comment]
As suggested above we don't think that _dot_ specific functionality should be places into this core tool.

It should be a very low amount of work (less than an hour) to take the code from this pull request and put it into a new package and release it as a standalone tool which uses the public API of rospack. But the author of the pull request seemed to not have done that.

**Pull request closed without merging**
