### PR TITLE
Handle None as return value for call_pkg_config

### PR DESCRIPTION
**Pull request by roehling**
Part of a proposed fix for ros/rosdep#34

A failed call to pkg-config should give a more
clear error message instead of a stack trace.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This pull request relies on ros/rosdep#227 to make sense.

**Comment by roehling** [comment]
Is the new message okay?

**Comment by dirk-thomas** [comment]
None of the other messages contain the message package and especially the message you changed does not fail because of the specific message but due to a general problem of not being able to invoke pkg-config.
I will commit a modified patch soon.

**Comment by roehling** [comment]
Actually, the None return value does not indicate a general problem but a non-zero exit code from pkg-config. According to the manual that means that pkg-config does not know the queried package. I think it would be a good idea to state this fact in the error message to ease troubleshooting.

**Pull request closed without merging**
