### PR TITLE
Add missing run_depend on roslib

### PR DESCRIPTION
**Pull request by cottsay**
rospack doesn't generate any error if roslib isn't installed, but it is unable to find any packages without it

I would appreciate a backport to hydro and groovy for this one

### CODE REVIEW

**Comment by cottsay** [comment]
For whatever reason I thought that this was isolated, but it looks like it is failing builds on the farm, too. See:
- http://jenkins.ros.org/job/ros-hydro-libpcan_binarydeb_raring_amd64/2/console
- http://jenkins.ros.org/job/ros-hydro-libphidgets_binarydeb_raring_amd64/2/console

Clearly rospack and mk get installed, but when rospack is used to find mk, it fails to do so.

I hit the same problem on Fedora and ensuring that roslib was installed fixed it entirely.

**Comment by dirk-thomas** [comment]
Actually `roslib` depends on `rospack` (https://github.com/ros/ros/blob/indigo-devel/core/roslib/package.xml) which mean this PR would generate a circular dependency and therefore _not_ be merged anyway. I will therefore close this PR.

I think the actual problem here is that you are trying to do some highly discouraged stuff in your package, e.g. downloading external code in the build process (which are not unit test data). Your process requires rospack to be able to resolve other packages at build time which is not supported.

In order to make your packages build as they are you must `build_depend` on `roslib`. But you might want to consider refactoring your whole CMake process for these packages.

**Comment by cottsay** [comment]
Thanks, @dirk-thomas, I'll make sure the package's maintainers are aware of this.

**Comment by dirk-thomas** [comment]
Oh, I assumed these are your packages :wink: 
It would be great if you can inform the maintainers. Thanks.

**Comment by cottsay** [comment]
I'm just wading through the hydro packages and fixing compile problems on Fedora. Turns out that this one wasn't even compiling on Ubuntu... This will fix it though. Thanks again.

**Pull request closed without merging**
