### PR TITLE
Fix find_package(PythonLibs ...)

### PR DESCRIPTION
**Pull request by NikolausDemmel**
The version should be passed as argument, not by setting PythonLibs_FIND_VERSION.

This breaks builds in recentely released cmake 3.0.0 it seems: http://answers.ros.org/question/178375/linking-camera_info_manager-fails-on-osx/

This change should also be backported to groovy/hydro.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
@dirk-thomas: Thanks. Can you merge this into groovy-devel, or should I open a separate PR?

**Comment by dirk-thomas** [comment]
It wil be cherry-picked before a new release is done for those distros.

**Comment by NikolausDemmel** [comment]
Just curious: Is there some automatic process for this cherry-picking before release, or is this simply on someone's todo list for the release?

**Comment by dirk-thomas** [comment]
The maintainer manually decides what should be backported. There is no automatic process for it since the decision what goes in and what doesn't is usually based on a mixture of criteria: bug vs. feature, severity / complexity, potential of regressions...

I personally usually do this before making a new release. I also tend to wait some time for the patch to be available in the latest distro to reduce the risk of regressions.

**Comment by NikolausDemmel** [comment]
Makes sense. Thanks.

**Pull request merged**
